update: deploy.ssh

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -5,7 +5,7 @@ on:
     branches: [main]
 
 jobs:
-  deploy: # Одно Job, но с логичным порядком шагов
+  build: # Одно Job, но с логичным порядком шагов
     runs-on: ubuntu-latest
 
     steps:
@@ -16,115 +16,123 @@ jobs:
 
     - name: Set up Docker Buildx and Compose
       uses: docker/setup-buildx-action@v2
-
-    - name: Log in to Docker Hub
-      uses: docker/login-action@v2
-      with:
-        username: ${{ secrets.DOCKER_USERNAME }}
-        password: ${{ secrets.DOCKER_PASSWORD }}
     
     - name: Build Docker image
       run: docker compose build website
 
-      
-    - name: Verify Docker image was built
-      run: |
-        set -e
-        IMAGE_NAME="zhenyapetko/portfolio-site:latest"
-        echo "Verifying that image '$IMAGE_NAME' was built successfully..."
+  test:
+    runs-on: ubuntu-latest
+    needs: build
+    
+    steps:  
+      - name: Verify Docker image was built
+        run: |
+          set -e
+          IMAGE_NAME="zhenyapetko/portfolio-site:latest"
+          echo "Verifying that image '$IMAGE_NAME' was built successfully..."
         
 
-        docker image inspect "$IMAGE_NAME" > /dev/null 2>&1
+          docker image inspect "$IMAGE_NAME" > /dev/null 2>&1
         
-        if [ $? -eq 0 ]; then
+          if [ $? -eq 0 ]; then
             echo "Docker image '$IMAGE_NAME' found locally. Build verification passed."
-        else
+          else
             echo "Error: Docker image '$IMAGE_NAME' not found locally. Build verification failed."
             exit 1
-        fi
+          fi
+  
+  push:
+    runs-on: ubuntu-latest
+    needs: [build, test]
+    
+    steps:
+      - name: Push Docker image to Docker Hub
+        run: docker compose push website
+    
+  deploy:
+    runs-on: ubuntu-latest
+    needs: push
+    
+    steps:
 
+      - name: Set up SSH
+        uses: webfactory/ssh-agent@v0.5.3
+        with:
+          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
 
-    - name: Push Docker image to Docker Hub
-      run: docker compose push website
+      - name: Deploy to Server via SSH
+        env:
+          SSH_HOST: ${{ secrets.SSH_HOST }}
+          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
+          DOMAIN_NAME: ${{ secrets.DOMAIN_NAME }}
+          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
+          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
+          GIT_REPO_SSH_URL: "git@github.com:zhenyapetko/portfolio-site.git"
+          DOCKER_IMAGE_NAME: "zhenyapetko/portfolio-site:latest"
+          DEPLOY_PATH: "/opt/portfolio-site"
 
-    - name: Set up SSH
-      uses: webfactory/ssh-agent@v0.5.3
-      with:
-        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
-
-    - name: Deploy to Server via SSH
-      env:
-        SSH_HOST: ${{ secrets.SSH_HOST }}
-        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
-        DOMAIN_NAME: ${{ secrets.DOMAIN_NAME }}
-        DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
-        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
-        GIT_REPO_SSH_URL: "git@github.com:zhenyapetko/portfolio-site.git"
-        DOCKER_IMAGE_NAME: "zhenyapetko/portfolio-site:latest"
-        DEPLOY_PATH: "/opt/portfolio-site"
-
-      run: |
-        set -e
-
-        echo "Connecting to ${SSH_USERNAME}@${SSH_HOST}"
-
-        ssh -o StrictHostKeyChecking=no \
-            -o SendEnv=DOCKER_USER,DOCKER_PASSWORD,GIT_REPO_SSH_URL,DOCKER_IMAGE_NAME,DEPLOY_PATH,DOMAIN_NAME \
-            ${SSH_USERNAME}@${SSH_HOST} << EOF_SSH_SCRIPT
+        run: |
           set -e
 
-          echo "--- Выполнение скрипта деплоя на удаленном сервере ---"
+          echo "Connecting to ${SSH_USERNAME}@${SSH_HOST}"
+
+          ssh -o StrictHostKeyChecking=no \
+              -o SendEnv=DOCKER_USER,DOCKER_PASSWORD,GIT_REPO_SSH_URL,DOCKER_IMAGE_NAME,DEPLOY_PATH,DOMAIN_NAME \
+              ${SSH_USERNAME}@${SSH_HOST} << EOF_SSH_SCRIPT
+            set -e
+
+            echo "--- Выполнение скрипта деплоя на удаленном сервере ---"
           
-          if [ ! -d "${DEPLOY_PATH}/.git" ]; then
-            echo "Repository not found at ${DEPLOY_PATH}, cloning it..."
-            mkdir -p "${DEPLOY_PATH}" || { echo "ERROR: Failed to create directory ${DEPLOY_PATH}"; exit 1; }
-            git clone "${GIT_REPO_SSH_URL}" "${DEPLOY_PATH}" || { echo "ERROR: Failed to clone repository ${GIT_REPO_SSH_URL}"; exit 1; }
-          fi
+            if [ ! -d "${DEPLOY_PATH}/.git" ]; then
+              echo "Repository not found at ${DEPLOY_PATH}, cloning it..."
+              mkdir -p "${DEPLOY_PATH}" || { echo "ERROR: Failed to create directory ${DEPLOY_PATH}"; exit 1; }
+              git clone "${GIT_REPO_SSH_URL}" "${DEPLOY_PATH}" || { echo "ERROR: Failed to clone repository ${GIT_REPO_SSH_URL}"; exit 1; }
+            fi
           
           
-          cd "${DEPLOY_PATH}"
+            cd "${DEPLOY_PATH}"
 
           
-          git pull origin main
+            git pull origin main
 
-          docker system prune -af
-          docker volume prune -f
+            docker system prune -af
+            docker volume prune -f
           
-          docker compose down --remove-orphans 
+            docker compose down --remove-orphans 
 
-          echo "Logging into Docker Hub on EC2, username: ${DOCKER_USER}..."
-          echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USER}" --password-stdin
+            echo "Logging into Docker Hub on EC2, username: ${DOCKER_USER}..."
+            echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USER}" --password-stdin
 
           
-          docker pull "${DOCKER_IMAGE_NAME}"
-          docker compose up -d --force-recreate --remove-orphans
+            docker pull "${DOCKER_IMAGE_NAME}"
+            docker compose up -d --force-recreate --remove-orphans
           
-          echo "--- Docker Compose services started. ---"
+            echo "--- Docker Compose services started. ---"
           
-          echo "Deployment process finished."
-        EOF_SSH_SCRIPT
+            echo "Deployment process finished."
+          EOF_SSH_SCRIPT
 
-    - name: Send Telegram Notification (Success)
-      if: success()
-      uses: appleboy/telegram-action@master
-      with:
-        to: ${{ secrets.TG_CHAT_ID }}
-        token: ${{ secrets.TG_BOT_TOKEN }}
-        format: markdown
-        message: |
-          ✅ *Деплой успешен!*
+      - name: Send Telegram Notification (Success)
+        if: success()
+        uses: appleboy/telegram-action@master
+        with:
+          to: ${{ secrets.TG_CHAT_ID }}
+          token: ${{ secrets.TG_BOT_TOKEN }}
+          format: markdown
+          message: |
+            ✅ *Деплой успешен!*
           
-          [Перейти на сайт](http://${{ secrets.DOMAIN_NAME }})
-          [Посмотреть логи](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
+            [Перейти на сайт](http://${{ secrets.DOMAIN_NAME }})
+            [Посмотреть логи](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
     
-    - name: Send Telegram Notification (Failure)
-      if: failure()
-      uses: appleboy/telegram-action@master
-      with:
-        to: ${{ secrets.TG_CHAT_ID }}
-        token: ${{ secrets.TG_BOT_TOKEN }}
-        format: markdown
-        message: |
-          ❌ *Деплой провален!*
+      - name: Send Telegram Notification (Failure)
+        if: failure()
+        uses: appleboy/telegram-action@master
+        with:
+          to: ${{ secrets.TG_CHAT_ID }}
+          token: ${{ secrets.TG_BOT_TOKEN }}
+          format: markdown
+          message: |
+            ❌ *Деплой провален!*
           
-          [Посмотреть логи](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
+            [Посмотреть логи](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
