update: deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -17,48 +17,37 @@ jobs:
     - name: Set up Docker Buildx and Compose
       uses: docker/setup-buildx-action@v2
     
-    - name: Build Docker image
-      run: docker compose build website
-  
-    - name: Verify Docker image was built
-      run: |
-          set -e
-          IMAGE_NAME="zhenyapetko/portfolio-site:latest"
-          echo "Verifying that image '$IMAGE_NAME' was built successfully..."
-        
-
-          docker image inspect "$IMAGE_NAME" > /dev/null 2>&1
-        
-          if [ $? -eq 0 ]; then
-            echo "Docker image '$IMAGE_NAME' found locally. Build verification passed."
-          else
-            echo "Error: Docker image '$IMAGE_NAME' not found locally. Build verification failed."
-            exit 1
-          fi
-  
-  push:
-    runs-on: ubuntu-latest
-    needs: [build-and-test]
-    
-    steps:
-    - name: Checkout code
-      uses: actions/checkout@v3
-
-    - name: Set up Docker Buildx and Compose
-      uses: docker/setup-buildx-action@v2
-
     - name: Log in to Docker Hub
       uses: docker/login-action@v2
       with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
+    
+    - name: Build Docker image
+      run: docker compose build website
+  
+    - name: Verify Docker image was built
+      run: |
+        set -e
+        IMAGE_NAME="zhenyapetko/portfolio-site:latest"
+        echo "Verifying that image '$IMAGE_NAME' was built successfully..."
+        
+
+        docker image inspect "$IMAGE_NAME" > /dev/null 2>&1
+        
+        if [ $? -eq 0 ]; then
+          echo "Docker image '$IMAGE_NAME' found locally. Build verification passed."
+        else
+          echo "Error: Docker image '$IMAGE_NAME' not found locally. Build verification failed."
+          exit 1
+        fi
       
     - name: Push Docker image to Docker Hub
       run: docker compose push website
     
   deploy:
     runs-on: ubuntu-latest
-    needs: push
+    needs: build-and-test
     
     steps:
 
